<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Contensive.Addons.Newsletter</RootNamespace>
    <AssemblyName>aoNewsletter2</AssemblyName>
    <LangVersion>latest</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>newletter.snk</AssemblyOriginatorKeyFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Contensive.CPBaseClass" Version="26.7.11.31887" />
    <PackageReference Include="Contensive.DbModels" Version="26.7.11.31887" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.34" />
    <PackageReference Include="Nustache" Version="1.16.0.10" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Contensive.Addons.Newsletter.My.Resources</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>
</Project>
